---

- name: gnome | key shortcuts
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ item.name }}/{{ item.type }}"
    state: present
    value: "{{ item.value }}"
  with_items:
    - {name: 'custom0', type: 'command', value: "'/usr/bin/gnome-terminal'"}
    - {name: 'custom0', type: 'name', value: "'Terminal'"}
    - {name: 'custom0', type: 'binding', value: "'<Super>T'"}
    - {name: 'custom1', type: 'command', value: "'/usr/bin/nautilus'"}
    - {name: 'custom1', type: 'name', value: "'Files'"}
    - {name: 'custom1', type: 'binding', value: "'<Super>F'"}
  become: "{{ user }}"

- name: gnome | set bindings
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"
    state: present
  become: "{{ user }}"