---

- name: create various dirs
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ temp_dir }}"
    - "{{ home_dir }}/code"
    - "{{ home_dir}}/.config/fish"
  become: "{{ user }}"

- name: software | install!
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_software }} + {{ ansible_os_family | lower }}_software"

- import_tasks: "redhat.yaml"
  when: ansible_os_family == "Redhat"

- include_tasks: "{{ item }}"
  with_items:
    - hackfont/linux.yaml
    - vscode/vscode.yaml
    - gnome.yaml
    - nvim/nvim.yaml
    - tmux.yaml
