---

- name: create various dirs
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ temp_dir }}"
    - "{{ home_dir }}/code"
    - "{{ home_dir}}/.config/fish"
    - "{{ home_dir}}/.config/fish/functions"
  become_user: "{{ user }}"

- set_fact:
    distro_software: "{{ debian_software }}"
  when: ansible_os_family == "Debian"

- name: software | install!
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - "{{ common_software }}"
    - "{{ distro_software }}"

- import_tasks: "redhat.yaml"
  when: ansible_os_family == "Redhat"

- include_tasks: "{{ item }}"
  with_items:
    - fonts/linux.yaml
    - vscode/vscode.yaml
    - gnome.yaml
    - nvim/nvim.yaml
    - tmux.yaml
