---

- name: nvim | create dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ home_dir }}/.config/nvim/autoload"
  become: "{{ user }}"

- name: nvim | download vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home_dir }}/.config/nvim/autoload"
    mode: 0644
  become: "{{ user }}"